import type { UserStory, MockUser } from './types';

export const mockUsers: MockUser[] = [
  {
    id: '1',
    email: 'john.doe@example.com',
    fullName: 'John Doe',
    role: 'Member',
    registrationDate: '2025-10-15',
    lastLogin: '2025-10-29',
    verified: true,
    mfaEnabled: false,
  },
  {
    id: '2',
    email: 'jane.smith@example.com',
    fullName: 'Jane Smith',
    role: 'Admin',
    registrationDate: '2025-09-20',
    lastLogin: '2025-10-28',
    verified: true,
    mfaEnabled: true,
  },
];

export const userStories: UserStory[] = [
  {
    id: 'US-UM-001',
    title: 'User Account Registration',
    asA: 'new user',
    iWantTo: 'register for an account with my email and password',
    soThat: 'I can access the ToDo application',
    priority: 'High',
    storyPoints: 5,
    acceptanceCriteria: [
      { id: 'ac-1', text: 'User can access a registration page', completed: false },
      { id: 'ac-2', text: 'Registration form requires: email, password, confirm password, full name', completed: false },
      { id: 'ac-3', text: 'Email validation ensures proper email format', completed: false },
      { id: 'ac-4', text: 'Password validation requires minimum 8 characters, uppercase, lowercase, number, and special character', completed: false },
      { id: 'ac-5', text: 'Password and confirm password must match', completed: false },
      { id: 'ac-6', text: 'System prevents duplicate email registration', completed: false },
      { id: 'ac-7', text: 'User receives clear error messages for validation failures', completed: false },
      { id: 'ac-8', text: 'Successful registration creates user account with "Member" role by default', completed: false },
      { id: 'ac-9', text: 'User receives confirmation email after registration', completed: false },
      { id: 'ac-10', text: 'User is redirected to login page after successful registration', completed: false },
    ],
    technicalNotes: [
      'Use Formik + Yup for form validation',
      'Password should be hashed using bcrypt or PBKDF2 before storage',
      'Store user data in CosmosDB Users collection',
    ],
    steps: [
      { id: 'step-1', title: 'Registration Form', description: 'Fill out registration form with email, password, confirm password, and full name' },
      { id: 'step-2', title: 'Form Validation', description: 'System validates all inputs and shows errors if any' },
      { id: 'step-3', title: 'Success Message', description: 'User sees success message and confirmation email notification' },
      { id: 'step-4', title: 'Redirect to Login', description: 'User is redirected to login page' },
    ],
  },
  {
    id: 'US-UM-002',
    title: 'Email Verification',
    asA: 'newly registered user',
    iWantTo: 'verify my email address',
    soThat: 'the system can confirm my identity and enable full account access',
    priority: 'High',
    storyPoints: 3,
    acceptanceCriteria: [
      { id: 'ac-1', text: 'System sends verification email with unique token after registration', completed: false },
      { id: 'ac-2', text: 'Verification email contains a clickable link with embedded token', completed: false },
      { id: 'ac-3', text: 'User can click the verification link to verify their email', completed: false },
      { id: 'ac-4', text: 'Verification token expires after 24 hours', completed: false },
      { id: 'ac-5', text: 'System displays success message after successful verification', completed: false },
      { id: 'ac-6', text: 'User account is marked as verified in the database', completed: false },
      { id: 'ac-7', text: 'User can request a new verification email if token expires', completed: false },
    ],
    steps: [
      { id: 'step-1', title: 'Email Sent', description: 'System sends verification email to registered email address' },
      { id: 'step-2', title: 'Click Verification Link', description: 'User clicks the verification link in email' },
      { id: 'step-3', title: 'Verification Success', description: 'System displays success message and marks account as verified' },
    ],
  },
  {
    id: 'US-UM-004',
    title: 'User Login',
    asA: 'registered user',
    iWantTo: 'log in with my email and password',
    soThat: 'I can access my tasks and account',
    priority: 'High',
    storyPoints: 5,
    acceptanceCriteria: [
      { id: 'ac-1', text: 'User can access a login page', completed: false },
      { id: 'ac-2', text: 'Login form requires email and password', completed: false },
      { id: 'ac-3', text: 'System validates credentials against stored user data', completed: false },
      { id: 'ac-4', text: 'Successful login generates authentication token (JWT)', completed: false },
      { id: 'ac-5', text: 'User is redirected to dashboard after successful login', completed: false },
      { id: 'ac-6', text: 'Failed login displays clear error message', completed: false },
      { id: 'ac-7', text: '"Remember me" option extends session duration', completed: false },
    ],
    steps: [
      { id: 'step-1', title: 'Login Form', description: 'User enters email and password' },
      { id: 'step-2', title: 'Credential Validation', description: 'System validates credentials' },
      { id: 'step-3', title: 'Successful Login', description: 'User is redirected to dashboard' },
    ],
  },
  {
    id: 'US-UM-006',
    title: 'Password Reset Request',
    asA: 'user who forgot their password',
    iWantTo: 'request a password reset link',
    soThat: 'I can regain access to my account',
    priority: 'High',
    storyPoints: 3,
    acceptanceCriteria: [
      { id: 'ac-1', text: 'Login page displays "Forgot Password?" link', completed: false },
      { id: 'ac-2', text: 'User can enter their email address on password reset page', completed: false },
      { id: 'ac-3', text: 'System sends password reset email if account exists', completed: false },
      { id: 'ac-4', text: "System doesn't reveal whether email exists in the system (security)", completed: false },
      { id: 'ac-5', text: 'Password reset email contains unique, time-limited token', completed: false },
      { id: 'ac-6', text: 'Reset token expires after 1 hour', completed: false },
    ],
    steps: [
      { id: 'step-1', title: 'Reset Request Form', description: 'User enters email address' },
      { id: 'step-2', title: 'Confirmation Message', description: 'System displays confirmation message' },
      { id: 'step-3', title: 'Email Sent', description: 'Password reset email is sent (if account exists)' },
    ],
  },
  {
    id: 'US-UM-007',
    title: 'Password Reset Completion',
    asA: 'user with a password reset token',
    iWantTo: 'set a new password',
    soThat: 'I can regain access to my account',
    priority: 'High',
    storyPoints: 3,
    acceptanceCriteria: [
      { id: 'ac-1', text: 'User can click reset link from email', completed: false },
      { id: 'ac-2', text: 'System validates reset token is valid and not expired', completed: false },
      { id: 'ac-3', text: 'Reset page displays form for new password and confirm password', completed: false },
      { id: 'ac-4', text: 'Password validation follows same rules as registration', completed: false },
      { id: 'ac-5', text: 'Successful reset displays confirmation message', completed: false },
      { id: 'ac-6', text: 'User is redirected to login page after successful reset', completed: false },
    ],
    steps: [
      { id: 'step-1', title: 'Token Validation', description: 'System validates reset token' },
      { id: 'step-2', title: 'New Password Form', description: 'User enters new password and confirmation' },
      { id: 'step-3', title: 'Success & Redirect', description: 'Password updated successfully, redirect to login' },
    ],
  },
  {
    id: 'US-UM-010',
    title: 'View User Profile',
    asA: 'logged-in user',
    iWantTo: 'view my profile information',
    soThat: 'I can see my current account details',
    priority: 'High',
    storyPoints: 2,
    acceptanceCriteria: [
      { id: 'ac-1', text: 'User can access profile page from navigation menu', completed: false },
      { id: 'ac-2', text: 'Profile displays: full name, email, registration date, role', completed: false },
      { id: 'ac-3', text: 'Profile displays profile picture (if set)', completed: false },
      { id: 'ac-4', text: 'Profile displays account verification status', completed: false },
      { id: 'ac-5', text: 'Profile displays MFA status (enabled/disabled)', completed: false },
      { id: 'ac-6', text: 'Profile displays last login date/time', completed: false },
    ],
    steps: [
      { id: 'step-1', title: 'Navigate to Profile', description: 'User clicks profile link in navigation' },
      { id: 'step-2', title: 'View Profile Information', description: 'Profile page displays all user information' },
    ],
  },
];
